id: template_chat_flow
name: Template Chat Flow
environment:
  python_requirements_txt: requirements.txt
inputs:
  chat_history:
    type: list
    default: []
    is_chat_input: false
    is_chat_history: true
  query:
    type: string
    default: ""
    is_chat_input: true
outputs:
  reply:
    type: string
    reference: ${generateReply.output}
    is_chat_output: true
  documents:
    type: string
    reference: ${selectChunks.output}
nodes:
- name: formatRewriteIntentInputs
  type: python
  source:
    type: code
    path: formatConversationForIntentRewriting.py
  inputs:
    history: ${inputs.chat_history}
    max_tokens: 2000
    query: ${inputs.query}
  use_variants: false
- name: rewriteIntent
  type: llm
  source:
    type: code
    path: ragcore/prompt_templates/rewriteIntent.jinja2
  inputs:
    deployment_name: salekh-swedenc-gpt4o
    temperature: 0.7
    top_p: 0.95
    max_tokens: 120
    presence_penalty: 0
    frequency_penalty: 0
    conversation: ${formatRewriteIntentInputs.output}
  provider: AzureOpenAI
  connection: SAlekhOpenAISwedenC
  api: chat
  module: promptflow.tools.aoai
  use_variants: false
- name: extractSearchIntent
  type: python
  source:
    type: code
    path: extractSearchIntent.py
  inputs:
    intent: ${rewriteIntent.output}
  use_variants: false
- name: querySearchResource
  type: python
  source:
    type: package
    tool: promptflow_vectordb.tool.common_index_lookup.search
  inputs:
    mlindex_content: >
      embeddings:
        api_base: https://SAlekh-OpenAI-SwedenC.openai.azure.com/
        api_type: azure
        api_version: 2023-07-01-preview
        batch_size: '1'
        connection:
          id: /subscriptions/c9db0da4-80fe-4fad-bb5b-d8454b255d0c/resourceGroups/sa-rg-aiml/providers/Microsoft.MachineLearningServices/workspaces/sa-copilot-test-1/connections/SAlekhOpenAISwedenC
        connection_type: workspace_connection
        deployment: text-embedding-ada-002
        dimension: 1536
        kind: open_ai
        model: text-embedding-ada-002
        schema_version: '2'
      index:
        api_version: 2024-05-01-preview
        connection:
          id: /subscriptions/c9db0da4-80fe-4fad-bb5b-d8454b255d0c/resourceGroups/sa-rg-aiml/providers/Microsoft.MachineLearningServices/workspaces/sa-copilot-test-1/connections/sacognitivesearch1
        connection_type: workspace_connection
        endpoint: https://sa-cognitivesearch-1.search.windows.net/
        engine: azure-sdk
        field_mapping:
          content: chunk
          embedding: text_vector
          metadata: metadata
        index: arxiv-cs-index-ada2-vector
        kind: acs
        semantic_configuration_name: default
    queries: ${extractSearchIntent.output}
    query_type: Hybrid (vector + keyword)
    top_k: 10
  use_variants: false
- name: chunkDocuments
  type: python
  source:
    type: code
    path: chunkDocuments.py
  inputs:
    data_source: Azure AI Search
    max_tokens: 1050
    queries: ${extractSearchIntent.output}
    query_type: Hybrid (vector + keyword)
    results: ${querySearchResource.output}
    top_k: 10
  use_variants: false
- name: selectChunks
  type: python
  source:
    type: code
    path: filterChunks.py
  inputs:
    min_score: 0.3
    results: ${chunkDocuments.output}
    top_k: 10
  use_variants: false
- name: shouldGenerateReply
  type: python
  source:
    type: code
    path: shouldGenerateReply.py
  inputs:
    chunks: ${selectChunks.output}
    queries: ${extractSearchIntent.output}
  use_variants: false
- name: formatGenerateReplyInputs
  type: python
  source:
    type: code
    path: formatReplyInputs.py
  inputs:
    chunks: ${selectChunks.output}
    history: ${inputs.chat_history}
    max_conversation_tokens: 2000
    max_tokens: 5000
    query: ${inputs.query}
  use_variants: false
- name: generateReply
  type: llm
  source:
    type: code
    path: ragcore/prompt_templates/generateReply.jinja2
  inputs:
    inputs: ${formatGenerateReplyInputs.output}
    deployment_name: salekh-swedenc-gpt4o
    temperature: 0.7
    top_p: 0.95
    max_tokens: 800
    presence_penalty: 0
    frequency_penalty: 0
    indomain: "True"
    role_info: You are an AI assistant that helps people find information.
  provider: AzureOpenAI
  connection: SAlekhOpenAISwedenC
  api: chat
  module: promptflow.tools.aoai
  activate:
    when: ${shouldGenerateReply.output}
    is: true
  use_variants: false
